# Generated by Django 5.1.2 on 2024-10-20 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('availability', 'Availability')], default='availability', max_length=15),
        ),
    ]
