# Generated by Django 5.1.2 on 2024-10-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_alter_category_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='file',
            field=models.ImageField(default=1, upload_to='attachments/'),
            preserve_default=False,
        ),
    ]
