# Generated by Django 5.1.2 on 2024-10-20 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_attachment_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='file',
        ),
    ]
