# Generated by Django 5.1.2 on 2024-10-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('email', 'Email'), ('telegram', 'Telegram'), ('facebook', 'Facebook')], max_length=255),
        ),
    ]
